name: C Lint

on:
  push:
    paths:
      - 'src/SERVER/**.c'

jobs:
  banana:
    runs-on: ubuntu-latest
    env:
      workdir: ./src/SERVER

    steps:
    - uses: actions/checkout@v3

    - name: Install Deps
      run: |
        sudo apt-get install docker.io
        sudo systemctl enable --now docker

    - name: Lint
      run: sudo docker run --rm -i -v "$PWD:/mnt/delivery" -v "$PWD:/mnt/reports" ghcr.io/epitech/coding-style-checker:latest /mnt/delivery /mnt/reports
      working-directory: ${{ env.workdir }}

    - name: Upload Lint Report
      uses: actions/upload-artifact@v3
      with:
        name: lint-report.log
        path: src/SERVER/coding-style-reports.log

    - name: Is error ?
      run: if [[ $(wc -l coding-style-reports.log) -gt 0 ]]; then exit 1; fi
      working-directory: ${{ env.workdir }}
