name: Publish

on: [push, pull_request]

env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-YEP-400-TLS-4-1-zappy-xavier.mitault.git

jobs:
  compil:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest

    steps:
    - uses: actions/checkout@v2

    - name: make
      run: timeout 2m make || exit 1

  publish:
    needs: [compil]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          ${{ env.MIRROR_URL }}
        ssh_private_key:
          ${{ secrets.SSH_KEY }}
