name: Py Lint

on:
  push:
    paths:
      - 'src/AI/**.py'

jobs:
  pyright:
    runs-on: ubuntu-latest
    env:
      workdir: ./src/AI

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyright
        make
      working-directory: ${{ env.workdir }}

    - name: Lint
      run: pyright ./zappy_ia ./zappy_ai.py
      working-directory: ${{ env.workdir }}

  ruff:
    runs-on: ubuntu-latest
    env:
      workdir: ./src/AI

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff

    - name: Lint
      run: ruff check .
      working-directory: ${{ env.workdir }}

  black:
    runs-on: ubuntu-latest
    env:
      workdir: ./src/AI

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Lint
      run: black --check .
      working-directory: ${{ env.workdir }}
